image: golang

pipelines:
  default:
    - step:
        script:
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/pingaling-monitoring/${BITBUCKET_REPO_SLUG}"
          - mkdir -p "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}"
          - go get ./...
          - go get github.com/stretchr/testify
          - cd "${PACKAGE_PATH}/pkg/pingaling"
          - go test -race -coverprofile=profile.out -covermode=atomic
          - curl -s https://codecov.io/bash | bash -s - -t ecd6078a-0484-4805-9d2a-6723e1043ef7
