image: golang

pipelines:
  default:
    - step:
        script:
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/pingaling-monitoring/${BITBUCKET_REPO_SLUG}"
          - mkdir -p "${PACKAGE_PATH}"
          - ln -s ${PWD} ${PACKAGE_PATH}
          - cd "${PACKAGE_PATH}"
          - go get ./...
          - go get github.com/stretchr/testify
          - go build -o pingaling
          - go test ./... -v